### ISSUE TITLE
Are multiple forks possible?

### ISSUE THREAD

**Issue by Ryandaydev** [GSA/api-documentation-template#27]
Seems like a user is limited to one fork of the repo. Is the GSA org limited to only one? (Ryan sent email to GitHub support.)

**Comment by jfredrickson5** [comment]
One workaround would be to instruct users to clone the repo and push to their own new Git repository. Basically, create a duplicate. Downside is that it's more complicated for users to sync updates from this repo to theirs, and to contribute PRs back from their repo to this repo.

**Comment by Ryandaydev** [comment]
Thanks Jeff. The cloning might work because it appears Github tracks the number of clones here:

https://github.com/GSA/api-documentation-template/graphs/traffic

We are discussing metrics so we want to be able to track usage. Maybe the Usage = clones + forks?

**Comment by Ryandaydev** [comment]
OK based on the feedback from Github, it looks like I will recommend to clone rather than fork.

Here's their instructions for duplicating:
https://help.github.com/articles/duplicating-a-repository/
