### ISSUE TITLE
Update formatting of JSON Response Bodies in Documentation

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/api-documentation-template#32]
Currently the response bodies do not wrap and are all contained on a single line. This makes reading the documentation difficult. Instead, the responses should be formatted across multiple lines so they are quick and easy to read for devs. Example below

````
{
  name: "response",
  createdDate: "2017-01-20",
  modifiedDate: "2017-01-22",
  tags: [
    "tag1",
    "tag2",
    "tag3"
  ]
}
````

**Comment by Ryandaydev** [comment]
First: thanks for reviewing and commenting.

Next question: which page is this issue referring to?
