### ISSUE TITLE
Example API Calls Should Denote Data Response Formats

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/api-documentation-template#33]
The first example on https://gsa.github.io/api-documentation-template/api-docs/console/ shows that you can call https://api.consumerfinance.gov:443/data. However, it does not tell you if you can request xml or json (both are supported). There should be a standard convention either in the summary of an API or on each request that identifies that data format.

**Comment by Ryandaydev** [comment]
These pages were replaced with a newer version. However I added a note about the type of response supported (JSON in this case).
